### ISSUE TITLE
SSL Mutual Authentication 

### ISSUE THREAD

**Issue by vicbrun** [OWASP/OWASP-WebScarab#17]
Dear All,

Trust you're fine. Please help with this issue I've been struggling with:

When trying to connect to an HTTPS whose certificate was issued by Verisign using Webscarab as proxy the browser crashes, which I rightly assumed it's due to certificate problem. So, I instructed Webscarab proxy listener to use that particular link as base url on port 443. This solved the problem partially, as the browser no longer crashes but, does not display the https page,just blank.

I googled  on the subject but it wasn't that clear. So, if you've something to share please....

Thanks and Regards,

Victor

**Comment by bradmills24** [comment]
Hello, I am actually now facing a similar problem with Web Scarab and as Rogan mentioned nothing worse than a thread that ends without an explanation of a solution. Would love to hear what you did in this situation Victor.

Thanks

**Comment by vicbrun** [comment]
Hello Brad!

My apologies to you and to everyone who've read this thread before. I never realised my solution was not posted, because as far as I remembered I had replied to Rogan immediately. Just got surprised my comment isn't there!

Anyway, what I did was re-compiling WebScarab:

1. Opened WebScarab.jar in a maven-capable IDE (I used netbeans) but anyone could help.

2. Run a clean and build with dependencies.

3. Let the IDE download maven dependencies and compile WebScarab.jar

4. After I got that "build success" message, it was done. When I ran WebScarab again, in stand-alone mode, outside IDE, everything worked fine.

Please never hesitate to contact

Regards,

Victor

 
Bruno Ronda

-----Original Message-----
