### ISSUE TITLE
Invalid security certificate SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by rakib-amin** [OWASP/OWASP-WebScarab#24]
This looks like pretty outdated repo, but if you are there listening, someone needs to open Gate 3.... sorry, someone needs to add a build process so that i can rebuild webscarab and add my own server.p12 file using these instruction: https://www.owasp.org/index.php/WebScarab_SSL_Certificates

**Comment by RoganDawes** [comment]
In fact, that page is also outdated. WebScarab automatically generates its own Certificate Authority, and uses that to sign certificates that it uses to intercept the SSL communications.

Obviously, since the CA cert is generated on a per-installation basis, all clients connecting through WebScarab will show this as untrusted (Unknown issuer). To solve this, you should import the CA cert into your browsers certificate store.

**Comment by rakib-amin** [comment]
![expiration_webscarab](https://cloud.githubusercontent.com/assets/16912635/23598243/602df83a-0263-11e7-82cf-49e27bf458f4.png)

Thanks So much for replying this quickly. `WebScarab now automatically generates its own Certificate Authority, and uses that to sign certificates that it uses to intercept the SSL communications.` It does, I know, and the cert it's using is expired. Now I did generate a ca_cert.pem of my own. I imported it to the certificate store. Then when Webscarab takes over and uses its own cert, the attachment picture happens.

**Comment by RoganDawes** [comment]
Hmmm. If you have been using Webscarab for a long time (10 years), your certificate should expire. I think I may have done something silly in the very early days, making it expire a bit earlier than that, based on the expiry date of an existing certificate.

The simplest solution is to delete your current CA cert which WebScarab saves to the file system, and let it generate a new one, then import that one into your browsers as if you were a new user.

The CA cert, and any certificates it signs are stored in the .keystore file. Removing that will trigger the generation process.

**Comment by rakib-amin** [comment]
Hi, was unable to do any of that. Couldn't find where webscarab CA is being stored. Nor the .keystore. I want to ask, is Zap (OWASP ZAP 2.5) a good alternative to WebScarab?

**Comment by RoganDawes** [comment]
It is likely to be in your home directory.

Zap is a good alternative if you are looking for something else.

**Comment by rakib-amin** [comment]
Thank you so much. I actually removed the `server.key` file from Users\ME (On a Windows machine). And then removed the existing WebScarab and reinstalled it using this installer. 
[webscarab-installer-20070504-1631.zip](https://github.com/OWASP/OWASP-WebScarab/files/820360/webscarab-installer-20070504-1631.zip)
