### ISSUE TITLE
connection not secure error

### ISSUE THREAD

**Issue by truesamurai** [OWASP/OWASP-WebScarab#28]
When using WebScarab proxy settings i get this error in my browser : Your connection is not secure
I guess its about the certification.
Which steps should I follow to proceed?

**Comment by RoganDawes** [comment]
Install the WebScarab CA certificate in your browser, so that it can
validate the certificate it automatically generates for each site you visit.

**Comment by sh1va73** [comment]
Thanks for your reply. I looked for that certificate but i cant find it. I must overlook something.

**Comment by RoganDawes** [comment]
Look in the directory containing WebScarab. There should be a CA file there.
