### ISSUE TITLE
Webscarab and the latest Mozilla version 121

### ISSUE THREAD

**Issue by johnny125** [OWASP/OWASP-WebScarab#31]
I tried to configure Webscarab in Mozilla Firefox Settings (latest Version 121) .However , it did not work . As I could not connect to the internet after configuring Mozilla version 121 . Does Webscarab even work with Mozilla latest version 121 ? There is no answer to this question in Google. That is why I asked the question .

**Comment by davewichers** [comment]
@johnny125 - why are you trying to use WebScarab, which hasn't been maintained much over the years? Have you tried ZAP, which was an OWASP project but recently moved? It is at: https://www.zaproxy.org. ZAP is a highly maintained open source web security testing proxy that is far more likely to provide you the capabilities you need.

**Comment by RoganDawes** [comment]
Dave is not wrong. I don't think WebScarab has seen any maintenance in the last 10 years or so! I'd strongly suggest looking at some of the other tools out there, of which Zap is a strong contender.

**Comment by johnny125** [comment]
Thank you . I will try Zap
